FROM adminer:latest

MAINTAINER Patrick Artounian <partounian@gmail.com>

USER root

RUN apk add --no-cache --virtual .php-ext-deps unixodbc freetds
RUN apk add --no-cache --virtual .build-deps unixodbc-dev freetds-dev
RUN docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr
RUN docker-php-ext-install pdo_odbc pdo_dblib
RUN apk del .build-deps && rm -rf /var/cache/apk/*

# Store PHP Configs at /usr/local/etc/php/conf.d
RUN echo "upload_max_filesize = 500M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "post_max_size = 500M"       >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "memory_limit = -1"           >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "max_execution_time = 0"      >> /usr/local/etc/php/conf.d/upload_large_dumps.ini

# Add volume for sessions to allow session persistence
VOLUME /sessions

USER adminer

CMD	[ "php", "-S", "[::]:8080", "-t", "/var/www/html" ]
# We expose Adminer on port 8080 (Adminer's default)
EXPOSE 8080
